<?php

namespace App\Http\Controllers\API\V1;

/**
 * @OA\Info(
 *     title="Schemas",
 *     version="1.0.0"
 * )
 */

/**
 * @OA\Components(
 *     @OA\Schema(
 *         schema="CreatePersonRequest",
 *         type="object",
 *         required={"personal_number", "full_name"},
 *         @OA\Property(property="personal_number", type="string"),
 *         @OA\Property(property="full_name", type="string"),
 *         @OA\Property(property="picture", type="string"),
 *         @OA\Property(property="vehicle", type="string")
 *     ),
 *     @OA\Schema(
 *         schema="UpdatePersonRequest",
 *         type="object",
 *         @OA\Property(property="personal_number", type="string"),
 *         @OA\Property(property="full_name", type="string"),
 *         @OA\Property(property="picture", type="string"),
 *         @OA\Property(property="vehicle", type="string")
 *     ),
 *     @OA\Schema(
 *         schema="PersonResource",
 *         type="object",
 *         @OA\Property(property="personal_number", type="string"),
 *         @OA\Property(property="full_name", type="string"),
 *         @OA\Property(property="picture", type="string"),
 *         @OA\Property(property="vehicle", type="string")
 *     ),
 *     @OA\Schema(
 *         schema="CreatePersonnelRequest",
 *         type="object",
 *         required={"first_name", "last_name", "badge_number", "hire_date", "role"},
 *         @OA\Property(property="first_name", type="string"),
 *         @OA\Property(property="last_name", type="string"),
 *         @OA\Property(property="rank", type="string"),
 *         @OA\Property(property="badge_number", type="string"),
 *         @OA\Property(property="hire_date", type="string"),
 *         @OA\Property(property="profile_image", type="string"),
 *         @OA\Property(property="role", type="string")
 *     ),
 *     @OA\Schema(
 *         schema="UpdatePersonnelRequest",
 *         type="object",
 *         @OA\Property(property="first_name", type="string"),
 *         @OA\Property(property="last_name", type="string"),
 *         @OA\Property(property="rank", type="string"),
 *         @OA\Property(property="badge_number", type="string"),
 *         @OA\Property(property="hire_date", type="string"),
 *         @OA\Property(property="profile_image", type="string"),
 *         @OA\Property(property="role", type="string")
 *     ),
 *     @OA\Schema(
 *         schema="PersonnelsResource",
 *         type="object",
 *         @OA\Property(property="first_name", type="string"),
 *         @OA\Property(property="last_name", type="string"),
 *         @OA\Property(property="rank", type="string"),
 *         @OA\Property(property="badge_number", type="string"),
 *         @OA\Property(property="hire_date", type="string"),
 *         @OA\Property(property="profile_image", type="string"),
 *         @OA\Property(property="role", type="string")
 *     ),
 *     @OA\Schema(
 *          schema="CreateRoleRequest",
 *          type="object",
 *          required={"role_title"},
 *          @OA\Property(property="role_title", type="string"),
 *          @OA\Property(property="role_description", type="string"),
 *      ),
 *      @OA\Schema(
 *          schema="UpdateRoleRequest",
 *          type="object",
 *          @OA\Property(property="role_title", type="string"),
 *          @OA\Property(property="role_description", type="string"),
 *      ),
 *      @OA\Schema(
 *          schema="RolesResource",
 *          type="object",
 *          @OA\Property(property="role_title", type="string"),
 *          @OA\Property(property="role_description", type="string"),
 *     ),
 *     @OA\Schema(
 *          schema="CreateTicketRequest",
 *          type="object",
 *          required={"description", "title", "price", "assigned_personnel", "vehicle", "person"},
 *          @OA\Property(property="description", type="string"),
 *          @OA\Property(property="title", type="string"),
 *          @OA\Property(property="price", type="string"),
 *          @OA\Property(property="assigned_personnel", type="string"),
 *          @OA\Property(property="vehicle", type="string"),
 *          @OA\Property(property="person", type="string"),
 *      ),
 *      @OA\Schema(
 *          schema="UpdateTicketRequest",
 *          type="object",
 *          @OA\Property(property="description", type="string"),
 *          @OA\Property(property="title", type="string"),
 *          @OA\Property(property="price", type="string"),
 *          @OA\Property(property="assigned_personnel", type="string"),
 *          @OA\Property(property="vehicle", type="string"),
 *          @OA\Property(property="person", type="string"),
 *      ),
 *      @OA\Schema(
 *          schema="TicketsResource",
 *          type="object",
 *          @OA\Property(property="description", type="string"),
 *          @OA\Property(property="title", type="string"),
 *          @OA\Property(property="price", type="string"),
 *          @OA\Property(property="assigned_personnel", type="string"),
 *          @OA\Property(property="vehicle", type="string"),
 *          @OA\Property(property="person", type="string"),
 *      ),
 *     @OA\Schema(
 *          schema="RegisterRequest",
 *          type="object",
 *          required={"username", "email", "password"},
 *          @OA\Property(property="username", type="string"),
 *          @OA\Property(property="email", type="string"),
 *          @OA\Property(property="password", type="string"),
 *          @OA\Property(property="name", type="string"),
 *          @OA\Property(property="device_id", type="integer")
 *      ),
 *      @OA\Schema(
 *          schema="LoginRequest",
 *          type="object",
 *          required={"username", "password"},
 *          @OA\Property(property="username", type="string"),
 *          @OA\Property(property="password", type="string")
 *      ),
 *      @OA\Schema(
 *          schema="ChangePasswordRequest",
 *          type="object",
 *          required={"current_password", "new_password"},
 *          @OA\Property(property="current_password", type="string"),
 *          @OA\Property(property="new_password", type="string")
 *      ),
 *      @OA\Schema(
 *          schema="UserResource",
 *          type="object",
 *          @OA\Property(property="id", type="integer"),
 *          @OA\Property(property="username", type="string"),
 *          @OA\Property(property="email", type="string"),
 *          @OA\Property(property="name", type="string")
 *      ),
 *     @OA\Schema(
 *      schema="CreateVehicleRequest",
 *      type="object",
 *      required={"vehicle_registration", "manufacture_name", "serie", "type", "produced_date", "purchased_date"},
 *      @OA\Property(property="vehicle_registration", type="string"),
 *      @OA\Property(property="manufacture_name", type="string"),
 *      @OA\Property(property="serie", type="string"),
 *      @OA\Property(property="type", type="string"),
 *      @OA\Property(property="produced_date", type="string", format="date"),
 *      @OA\Property(property="purchased_date", type="string", format="date"),
 *      @OA\Property(property="registration_date", type="string", format="date", nullable=true),
 *      @OA\Property(property="designated_driver", type="integer", nullable=true, description="ID of the designated driver"),
 *      @OA\Property(property="car_picture", type="string", nullable=true),
 *      @OA\Property(property="car_location", type="integer", nullable=true, description="ID of the car location")
 *  ),
 *      @OA\Schema(
 *      schema="UpdateVehicleRequest",
 *      type="object",
 *      @OA\Property(property="vehicle_registration", type="string", nullable=true),
 *      @OA\Property(property="manufacture_name", type="string", nullable=true),
 *      @OA\Property(property="serie", type="string", nullable=true),
 *      @OA\Property(property="type", type="string", nullable=true),
 *      @OA\Property(property="produced_date", type="string", format="date", nullable=true),
 *      @OA\Property(property="purchased_date", type="string", format="date", nullable=true),
 *      @OA\Property(property="registration_date", type="string", format="date", nullable=true),
 *      @OA\Property(property="designated_driver", type="integer", nullable=true, description="ID of the designated driver"),
 *      @OA\Property(property="car_picture", type="string", nullable=true),
 *      @OA\Property(property="car_location", type="integer", nullable=true, description="ID of the car location")
 *  ),
 *     @OA\Schema(
 *      schema="VehiclesResource",
 *      type="object",
 *      @OA\Property(property="id", type="integer"),
 *      @OA\Property(property="vehicle_registration", type="string"),
 *      @OA\Property(property="manufacture_name", type="string"),
 *      @OA\Property(property="serie", type="string"),
 *      @OA\Property(property="type", type="string"),
 *      @OA\Property(property="produced_date", type="string", format="date"),
 *      @OA\Property(property="purchased_date", type="string", format="date"),
 *      @OA\Property(property="registration_date", type="string", format="date", nullable=true),
 *      @OA\Property(property="designated_driver", type="integer", nullable=true),
 *      @OA\Property(property="car_picture", type="string", nullable=true),
 *      @OA\Property(property="car_location", type="integer", nullable=true)
 *  ),
 *          @OA\Schema(
 *          schema="CreateNewsRequest",
 *          type="object",
 *          required={"title", "content"},
 *          @OA\Property(property="title", type="string"),
 *          @OA\Property(property="content", type="string"),
 *          @OA\Property(property="tags", type="array", @OA\Items(type="string")),
 *          @OA\Property(property="image", type="string", format="binary")
 *      ),
 *      @OA\Schema(
 *          schema="UpdateNewsRequest",
 *          type="object",
 *          @OA\Property(property="title", type="string"),
 *          @OA\Property(property="content", type="string"),
 *          @OA\Property(property="tags", type="array", @OA\Items(type="string")),
 *          @OA\Property(property="image", type="string", format="binary")
 *      ),
 *      @OA\Schema(
 *          schema="NewsResource",
 *          type="object",
 *          @OA\Property(property="id", type="integer"),
 *          @OA\Property(property="title", type="string"),
 *          @OA\Property(property="content", type="string"),
 *          @OA\Property(property="tags", type="array", @OA\Items(type="string")),
 *          @OA\Property(property="image_url", type="string"),
 *          @OA\Property(property="views", type="integer"),
 *          @OA\Property(property="created_by", type="string"),
 *          @OA\Property(property="created_at", type="string", format="date-time"),
 *          @OA\Property(property="updated_at", type="string", format="date-time")
 *      ),
 *          @OA\Schema(
 *          schema="CreateMessageRequest",
 *          type="object",
 *          required={"content"},
 *          @OA\Property(property="content", type="string", maxLength=5000)
 *      ),
 *      @OA\Schema(
 *          schema="MessageResource",
 *          type="object",
 *          @OA\Property(property="message_id", type="string"),
 *          @OA\Property(property="sender", ref="#/components/schemas/UserResource"),
 *          @OA\Property(property="content", type="string"),
 *          @OA\Property(property="type", type="string"),
 *          @OA\Property(property="created_at", type="string", format="date-time"),
 *          @OA\Property(property="updated_at", type="string", format="date-time")
 *      ),
 *          @OA\Schema(
 *          schema="CreateLocationRequest",
 *          type="object",
 *          required={"name", "address", "longitude", "latitude", "radius"},
 *          @OA\Property(property="name", type="integer"),
 *          @OA\Property(property="address", type="string"),
 *          @OA\Property(property="longitude", type="string"),
 *          @OA\Property(property="latitude", type="string"),
 *          @OA\Property(property="radius", type="integer")
 *      ),
 *      @OA\Schema(
 *          schema="UpdateLocationRequest",
 *          type="object",
 *          @OA\Property(property="name", type="integer"),
 *          @OA\Property(property="address", type="string"),
 *          @OA\Property(property="longitude", type="string"),
 *          @OA\Property(property="latitude", type="string"),
 *          @OA\Property(property="radius", type="integer")
 *      ),
 *      @OA\Schema(
 *          schema="LocationResource",
 *          type="object",
 *          @OA\Property(property="id", type="integer"),
 *          @OA\Property(property="name", type="integer"),
 *          @OA\Property(property="address", type="string"),
 *          @OA\Property(property="longitude", type="string"),
 *          @OA\Property(property="latitude", type="string"),
 *          @OA\Property(property="radius", type="integer")
 *      ),
 *      @OA\Schema(
 *          schema="CreateIncidentRequest",
 *          type="object",
 *          required={"reporter_id"},
 *          @OA\Property(property="incident_type", type="string"),
 *          @OA\Property(property="description", type="string"),
 *          @OA\Property(property="location", type="string"),
 *          @OA\Property(property="report_date_time", type="string", format="date-time"),
 *          @OA\Property(property="reporter_id", type="string"),
 *          @OA\Property(property="participants_id", type="string"),
 *          @OA\Property(property="vehicles_number", type="string"),
 *      ),
 *      @OA\Schema(
 *          schema="UpdateIncidentRequest",
 *          type="object",
 *          @OA\Property(property="incident_type", type="string"),
 *          @OA\Property(property="description", type="string"),
 *          @OA\Property(property="location", type="string"),
 *          @OA\Property(property="report_date_time", type="string"),
 *          @OA\Property(property="reporter_id", type="string"),
 *          @OA\Property(property="participants_id", type="string"),
 *          @OA\Property(property="vehicles_number", type="string"),
 *      ),
 *      @OA\Schema(
 *          schema="IncidentResource",
 *          type="object",
 *          @OA\Property(property="incident_id", type="integer"),
 *          @OA\Property(property="incident_type", type="string"),
 *          @OA\Property(property="description", type="string"),
 *          @OA\Property(property="location", type="string"),
 *          @OA\Property(property="report_date_time", type="string", format="date-time"),
 *          @OA\Property(property="reporter_id", type="string"),
 *          @OA\Property(property="participants_id", type="string"),
 *          @OA\Property(property="vehicles_number", type="string"),
 *      ),
 *      @OA\Schema(
 *          schema="CreateEquipmentRequest",
 *          type="object",
 *          required={"name", "quantity"},
 *          @OA\Property(property="name", type="string"),
 *          @OA\Property(property="quantity", type="integer"),
 *          @OA\Property(property="description", type="string"),
 *      ),
 *      @OA\Schema(
 *          schema="UpdateEquipmentRequest",
 *          type="object",
 *          @OA\Property(property="name", type="string"),
 *          @OA\Property(property="quantity", type="integer"),
 *          @OA\Property(property="description", type="string"),
 *      ),
 *      @OA\Schema(
 *          schema="EquipmentsResource",
 *          type="object",
 *          @OA\Property(property="equipment_id", type="string"),
 *          @OA\Property(property="name", type="string"),
 *          @OA\Property(property="quantity", type="integer"),
 *          @OA\Property(property="description", type="string"),
 *      ),
 *      @OA\Schema(
 *          schema="CreateAttendanceRequest",
 *          type="object",
 *          required={"personnel_id", "attendance_date", "entry_time", "missed_entry"},
 *          @OA\Property(property="personnel_id", type="integer"),
 *          @OA\Property(property="attendance_date", type="string"),
 *          @OA\Property(property="entry_time", type="string"),
 *          @OA\Property(property="missed_entry", type="string")
 *      ),
 *      @OA\Schema(
 *          schema="UpdateAttendanceRequest",
 *          type="object",
 *          @OA\Property(property="personnel_id", type="integer"),
 *          @OA\Property(property="attendance_date", type="string"),
 *          @OA\Property(property="entry_time", type="string"),
 *          @OA\Property(property="missed_entry", type="string")
 *      ),
 *      @OA\Schema(
 *          schema="AttendanceResource",
 *          type="object",
 *          @OA\Property(property="attendance_id", type="integer"),
 *          @OA\Property(property="personnel_id", type="integer"),
 *          @OA\Property(property="attendance_date", type="string"),
 *          @OA\Property(property="entry_time", type="string"),
 *          @OA\Property(property="missed_entry", type="string")
 *      ),
 *      @OA\Schema(
 *          schema="CreateCampaignRequest",
 *          type="object",
 *          required={"title", "pdf"},
 *          @OA\Property(property="title", type="string", maxLength=255),
 *          @OA\Property(property="pdf", type="string", format="binary"),
 *      ),
 *      @OA\Schema(
 *          schema="UpdateCampaignRequest",
 *          type="object",
 *          @OA\Property(property="title", type="string", maxLength=255),
 *          @OA\Property(property="pdf", type="string", format="binary"),
 *      ),
 *      @OA\Schema(
 *          schema="CampaignResource",
 *          type="object",
 *          @OA\Property(property="campaign_id", type="integer"),
 *          @OA\Property(property="title", type="string", maxLength=255),
 *          @OA\Property(property="description", type="string"),
 *          @OA\Property(property="pdf_url", type="string", format="url"),
 *          @OA\Property(property="thumbnail_url", type="string", format="url"),
 *          @OA\Property(property="created_at", type="string", format="date-time"),
 *          @OA\Property(property="updated_at", type="string", format="date-time"),
 *      ),
 *      @OA\Schema(
 *          schema="CreateCaseRequest",
 *          type="object",
 *          required={"status", "open_date", "investigator_id", "incidents_id"},
 *          @OA\Property(property="status", type="string"),
 *          @OA\Property(property="open_date", type="string", format="date"),
 *          @OA\Property(property="close_date", type="string", format="date"),
 *          @OA\Property(property="investigator_id", type="string"),
 *          @OA\Property(property="incidents_id", type="string"),
 *      ),
 *      @OA\Schema(
 *         schema="UpdateCaseRequest",
 *         type="object",
 *         @OA\Property(property="status", type="string"),
 *         @OA\Property(property="open_date", type="string", format="date"),
 *         @OA\Property(property="close_date", type="string", format="date"),
 *         @OA\Property(property="investigator_id", type="string"),
 *         @OA\Property(property="incidents_id", type="string"),
 *      ),
 *     @OA\Schema(
 *         schema="CasesResource",
 *         type="object",
 *         @OA\Property(property="case_id", type="integer"),
 *         @OA\Property(property="status", type="string"),
 *         @OA\Property(property="open_date", type="string", format="date"),
 *         @OA\Property(property="close_date", type="string", format="date"),
 *         @OA\Property(property="investigator_id", type="string"),
 *         @OA\Property(property="incidents_id", type="string"),
 *         @OA\Property(property="created_at", type="string", format="date-time"),
 *         @OA\Property(property="updated_at", type="string", format="date-time"),
 *     ),
 *     @OA\Schema(
 *         schema="ConversationResource",
 *         type="object",
 *         @OA\Property(property="conversation_id", type="string"),
 *         @OA\Property(property="conversation_name", type="string"),
 *         @OA\Property(property="conversation_picture", type="string"),
 *         @OA\Property(property="users", type="array", @OA\Items(ref="#/components/schemas/UserResource")),
 *      ),
 *      @OA\Schema(
 *         schema="CreateDepartmentRequest",
 *         type="object",
 *         required={"department_name", "department_logo", "description"},
 *         @OA\Property(property="department_name", type="string"),
 *         @OA\Property(property="department_logo", type="string"),
 *         @OA\Property(property="description", type="string"),
 *      ),
 *      @OA\Schema(
 *         schema="UpdateDepartmentRequest",
 *         type="object",
 *         @OA\Property(property="department_name", type="string"),
 *         @OA\Property(property="department_logo", type="string"),
 *         @OA\Property(property="description", type="string"),
 *      ),
 *      @OA\Schema(
 *         schema="DepartmentsResource",
 *         type="object",
 *         @OA\Property(property="department_id", type="integer"),
 *         @OA\Property(property="department_name", type="string"),
 *         @OA\Property(property="department_logo", type="string"),
 *         @OA\Property(property="description", type="string"),
 *      ),
 *       @OA\Schema(
 *         schema="DepartmentPersonnelResource",
 *         type="object",
 *         @OA\Property(property="department_id", type="integer"),
 *         @OA\Property(property="personnel_id", type="integer"),
 *         @OA\Property(property="personnels", type="array", @OA\Items(ref="#/components/schemas/PersonnelsResource")),
 *         @OA\Property(property="departments", type="array", @OA\Items(ref="#/components/schemas/DepartmentsResource")),
 *     ),
 *      @OA\Schema(
 *         schema="CreateEmergencyCallRequest",
 *         type="object",
 *         required={"caller_name", "phone_number", "incident_type", "location", "time", "responder"},
 *         @OA\Property(property="caller_name", type="string"),
 *         @OA\Property(property="phone_number", type="string"),
 *         @OA\Property(property="incident_type", type="string"),
 *         @OA\Property(property="location", type="integer", format="int64"),
 *         @OA\Property(property="time", type="string", format="date-time"),
 *         @OA\Property(property="responder", type="integer", format="int64"),
 *      ),
 *      @OA\Schema(
 *         schema="UpdateEmergencyCallRequest",
 *         type="object",
 *         @OA\Property(property="caller_name", type="string"),
 *         @OA\Property(property="phone_number", type="string"),
 *         @OA\Property(property="incident_type", type="string"),
 *         @OA\Property(property="location", type="integer", format="int64", nullable=true),
 *         @OA\Property(property="time", type="string", format="date-time", nullable=true),
 *         @OA\Property(property="responder", type="integer", format="int64", nullable=true),
 *     ),
 *      @OA\Schema(
 *         schema="EmergencyCallResource",
 *         type="object",
 *         @OA\Property(property="call_id", type="integer"),
 *         @OA\Property(property="caller_name", type="string"),
 *         @OA\Property(property="phone_number", type="string"),
 *         @OA\Property(property="incident_type", type="string"),
 *         @OA\Property(property="location", type="integer", format="int64"),
 *         @OA\Property(property="time", type="string", format="date-time"),
 *         @OA\Property(property="responder", type="integer", format="int64"),
 *  )
 *
 * )
 */
class OpenApiAnnotations
{
    // This class is only for OpenAPI annotations
}
